### ISSUE TITLE
help

### ISSUE THREAD

**Issue by linghubingli** [ROCm/rocm-install-on-windows#68]
我安装了HIP SDK，但是我的文件夹下没有rocminfo.exe，我的设备是AMD RX 6750 GRE 12G，我想用来训练YOLO模型，可行吗，如果回复我，请投递到1544192510@qq.com，非常感谢

I installed the HIP SDK, but there is no rocminfo.exe under my folder, my device is AMD RX 6750 GRE 12G, I want to use it to train YOLO, is it possible, if you reply to me, please send it to the 1544192510@qq.com, thank you very much

**Comment by harkgill-amd** [comment]
Hi @Smart-huhu, this was answered at https://github.com/ROCm/ROCm/issues/4024#issuecomment-2468477121.
